const polyline = require('@mapbox/polyline');

const stopDefinitions = [
  {
    stop_id: 'HRY-STP-SNP-BS',
    name: 'Sonipat Bus Stand',
    latitude: 28.9931,
    longitude: 77.0151,
    city: 'Sonipat',
    platforms: ['A', 'B', 'C', 'D'],
  },
  {
    stop_id: 'DLH-STP-ISBT-KG',
    name: 'ISBT Kashmere Gate',
    latitude: 28.6676,
    longitude: 77.2273,
    city: 'Delhi',
    platforms: ['1', '2', '3', '4', '5'],
  },
  {
    stop_id: 'HRY-STP-PNP-BS',
    name: 'Panipat Bus Stand',
    latitude: 29.3909,
    longitude: 76.9635,
    city: 'Panipat',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-KNL-BS',
    name: 'Karnal Bus Stand',
    latitude: 29.6857,
    longitude: 76.9905,
    city: 'Karnal',
    platforms: ['A', 'B', 'C', 'D'],
  },
  {
    stop_id: 'HRY-STP-KKR-BS',
    name: 'Kurukshetra Bus Stand',
    latitude: 29.9695,
    longitude: 76.8783,
    city: 'Kurukshetra',
    platforms: ['A', 'B'],
  },
  {
    stop_id: 'HRY-STP-RTK-BS',
    name: 'Rohtak Bus Stand',
    latitude: 28.8955,
    longitude: 76.6066,
    city: 'Rohtak',
    platforms: ['A', 'B', 'C', 'D'],
  },
  {
    stop_id: 'HRY-STP-GGN-BS',
    name: 'Gurugram Bus Stand',
    latitude: 28.4595,
    longitude: 77.0266,
    city: 'Gurugram',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-HSR-BS',
    name: 'Hisar Bus Stand',
    latitude: 29.1492,
    longitude: 75.7217,
    city: 'Hisar',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'CHD-STP-SEC17',
    name: 'Chandigarh Sector 17 ISBT',
    latitude: 30.7333,
    longitude: 76.7794,
    city: 'Chandigarh',
    platforms: ['A', 'B', 'C', 'D'],
  },
  {
    stop_id: 'HRY-STP-AMB-BS',
    name: 'Ambala City Bus Stand',
    latitude: 30.3782,
    longitude: 76.7767,
    city: 'Ambala',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-FBD-BS',
    name: 'Faridabad NIT Bus Stand',
    latitude: 28.4089,
    longitude: 77.3178,
    city: 'Faridabad',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-JND-BS',
    name: 'Jind Bus Stand',
    latitude: 29.3152,
    longitude: 76.315,
    city: 'Jind',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-BHW-BS',
    name: 'Bhiwani Bus Stand',
    latitude: 28.793,
    longitude: 76.1397,
    city: 'Bhiwani',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-SRS-BS',
    name: 'Sirsa Bus Stand',
    latitude: 29.5349,
    longitude: 75.0289,
    city: 'Sirsa',
    platforms: ['A', 'B'],
  },
  {
    stop_id: 'HRY-STP-YNR-BS',
    name: 'Yamunanagar Bus Stand',
    latitude: 30.129,
    longitude: 77.2674,
    city: 'Yamunanagar',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-RWR-BS',
    name: 'Rewari Bus Stand',
    latitude: 28.192,
    longitude: 76.6198,
    city: 'Rewari',
    platforms: ['A', 'B', 'C'],
  },
  {
    stop_id: 'HRY-STP-NNL-BS',
    name: 'Narnaul Bus Stand',
    latitude: 28.0446,
    longitude: 76.108,
    city: 'Narnaul',
    platforms: ['A', 'B'],
  },
  {
    stop_id: 'HRY-STP-JJR-BS',
    name: 'Jhajjar Bus Stand',
    latitude: 28.6063,
    longitude: 76.6565,
    city: 'Jhajjar',
    platforms: ['A', 'B'],
  },
];

const routeDefinitions = [
  {
    route_id: 'HRY-RTE-001',
    route_name: 'Sonipat -> ISBT Delhi',
    stops: ['HRY-STP-SNP-BS', 'DLH-STP-ISBT-KG'],
    distance_km: 47,
    estimated_time_minutes: 95,
  },
  {
    route_id: 'HRY-RTE-002',
    route_name: 'Panipat -> Karnal -> Kurukshetra',
    stops: ['HRY-STP-PNP-BS', 'HRY-STP-KNL-BS', 'HRY-STP-KKR-BS'],
    distance_km: 77,
    estimated_time_minutes: 130,
  },
  {
    route_id: 'HRY-RTE-003',
    route_name: 'Rohtak -> Gurugram -> Delhi',
    stops: ['HRY-STP-RTK-BS', 'HRY-STP-GGN-BS', 'DLH-STP-ISBT-KG'],
    distance_km: 86,
    estimated_time_minutes: 150,
  },
  {
    route_id: 'HRY-RTE-004',
    route_name: 'Hisar -> Rohtak -> Delhi',
    stops: ['HRY-STP-HSR-BS', 'HRY-STP-RTK-BS', 'DLH-STP-ISBT-KG'],
    distance_km: 175,
    estimated_time_minutes: 285,
  },
  {
    route_id: 'HRY-RTE-005',
    route_name: 'Chandigarh -> Ambala -> Karnal',
    stops: ['CHD-STP-SEC17', 'HRY-STP-AMB-BS', 'HRY-STP-KNL-BS'],
    distance_km: 122,
    estimated_time_minutes: 205,
  },
  {
    route_id: 'HRY-RTE-006',
    route_name: 'Faridabad -> Gurugram -> Delhi',
    stops: ['HRY-STP-FBD-BS', 'HRY-STP-GGN-BS', 'DLH-STP-ISBT-KG'],
    distance_km: 70,
    estimated_time_minutes: 145,
  },
  {
    route_id: 'HRY-RTE-007',
    route_name: 'Jind -> Rohtak -> Gurugram',
    stops: ['HRY-STP-JND-BS', 'HRY-STP-RTK-BS', 'HRY-STP-GGN-BS'],
    distance_km: 118,
    estimated_time_minutes: 215,
  },
  {
    route_id: 'HRY-RTE-008',
    route_name: 'Bhiwani -> Rohtak -> Sonipat',
    stops: ['HRY-STP-BHW-BS', 'HRY-STP-RTK-BS', 'HRY-STP-SNP-BS'],
    distance_km: 110,
    estimated_time_minutes: 200,
  },
  {
    route_id: 'HRY-RTE-009',
    route_name: 'Sirsa -> Hisar -> Rohtak',
    stops: ['HRY-STP-SRS-BS', 'HRY-STP-HSR-BS', 'HRY-STP-RTK-BS'],
    distance_km: 205,
    estimated_time_minutes: 320,
  },
  {
    route_id: 'HRY-RTE-010',
    route_name: 'Yamunanagar -> Kurukshetra -> Karnal',
    stops: ['HRY-STP-YNR-BS', 'HRY-STP-KKR-BS', 'HRY-STP-KNL-BS'],
    distance_km: 95,
    estimated_time_minutes: 170,
  },
  {
    route_id: 'HRY-RTE-011',
    route_name: 'Rewari -> Jhajjar -> Rohtak',
    stops: ['HRY-STP-RWR-BS', 'HRY-STP-JJR-BS', 'HRY-STP-RTK-BS'],
    distance_km: 108,
    estimated_time_minutes: 195,
  },
  {
    route_id: 'HRY-RTE-012',
    route_name: 'Narnaul -> Rewari -> Gurugram',
    stops: ['HRY-STP-NNL-BS', 'HRY-STP-RWR-BS', 'HRY-STP-GGN-BS'],
    distance_km: 123,
    estimated_time_minutes: 220,
  },
];

const tripDefinitions = [
  {
    bus_id: 'HRY-BUS-101',
    route_id: 'HRY-RTE-001',
    occupancy: 'medium',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-202',
    route_id: 'HRY-RTE-002',
    occupancy: 'high',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-303',
    route_id: 'HRY-RTE-003',
    occupancy: 'low',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-404',
    route_id: 'HRY-RTE-004',
    occupancy: 'medium',
    status: 'delayed',
  },
  {
    bus_id: 'HRY-BUS-505',
    route_id: 'HRY-RTE-005',
    occupancy: 'low',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-606',
    route_id: 'HRY-RTE-006',
    occupancy: 'medium',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-707',
    route_id: 'HRY-RTE-007',
    occupancy: 'high',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-808',
    route_id: 'HRY-RTE-008',
    occupancy: 'medium',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-909',
    route_id: 'HRY-RTE-009',
    occupancy: 'high',
    status: 'delayed',
  },
  {
    bus_id: 'HRY-BUS-010',
    route_id: 'HRY-RTE-010',
    occupancy: 'low',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-011',
    route_id: 'HRY-RTE-011',
    occupancy: 'medium',
    status: 'running',
  },
  {
    bus_id: 'HRY-BUS-012',
    route_id: 'HRY-RTE-012',
    occupancy: 'low',
    status: 'running',
  },
];

const journeyDefinitions = [
  {
    journey_id: 'JRN-2741',
    route_id: 'HRY-RTE-001',
    bus_id: 'HRY-BUS-101',
    source_stop_id: 'HRY-STP-SNP-BS',
    destination_stop_id: 'DLH-STP-ISBT-KG',
    started_at: new Date('2026-04-17T08:15:00.000Z'),
    ended_at: new Date('2026-04-17T09:50:00.000Z'),
    duration_minutes: 95,
    fare_inr: 85,
    status: 'completed',
    payment_mode: 'upi',
  },
  {
    journey_id: 'JRN-2692',
    route_id: 'HRY-RTE-002',
    bus_id: 'HRY-BUS-202',
    source_stop_id: 'HRY-STP-PNP-BS',
    destination_stop_id: 'HRY-STP-KKR-BS',
    started_at: new Date('2026-04-16T12:10:00.000Z'),
    ended_at: new Date('2026-04-16T14:20:00.000Z'),
    duration_minutes: 130,
    fare_inr: 74,
    status: 'completed',
    payment_mode: 'upi',
  },
  {
    journey_id: 'JRN-2637',
    route_id: 'HRY-RTE-003',
    bus_id: 'HRY-BUS-303',
    source_stop_id: 'HRY-STP-RTK-BS',
    destination_stop_id: 'DLH-STP-ISBT-KG',
    started_at: new Date('2026-04-15T10:05:00.000Z'),
    ended_at: new Date('2026-04-15T12:35:00.000Z'),
    duration_minutes: 150,
    fare_inr: 96,
    status: 'completed',
    payment_mode: 'card',
  },
  {
    journey_id: 'JRN-2599',
    route_id: 'HRY-RTE-004',
    bus_id: 'HRY-BUS-404',
    source_stop_id: 'HRY-STP-HSR-BS',
    destination_stop_id: 'HRY-STP-RTK-BS',
    started_at: new Date('2026-04-14T07:30:00.000Z'),
    ended_at: new Date('2026-04-14T10:25:00.000Z'),
    duration_minutes: 175,
    fare_inr: 132,
    status: 'completed',
    payment_mode: 'cash',
  },
  {
    journey_id: 'JRN-2558',
    route_id: 'HRY-RTE-006',
    bus_id: 'HRY-BUS-606',
    source_stop_id: 'HRY-STP-FBD-BS',
    destination_stop_id: 'DLH-STP-ISBT-KG',
    started_at: new Date('2026-04-13T17:20:00.000Z'),
    ended_at: new Date('2026-04-13T19:45:00.000Z'),
    duration_minutes: 145,
    fare_inr: 88,
    status: 'completed',
    payment_mode: 'upi',
  },
  {
    journey_id: 'JRN-2502',
    route_id: 'HRY-RTE-009',
    bus_id: 'HRY-BUS-909',
    source_stop_id: 'HRY-STP-SRS-BS',
    destination_stop_id: 'HRY-STP-RTK-BS',
    started_at: new Date('2026-04-12T06:50:00.000Z'),
    ended_at: new Date('2026-04-12T12:10:00.000Z'),
    duration_minutes: 320,
    fare_inr: 188,
    status: 'completed',
    payment_mode: 'upi',
  },
];

function buildRoutesWithGeometry() {
  const stopMap = new Map(stopDefinitions.map((s) => [s.stop_id, s]));

  return routeDefinitions.map((route) => {
    const points = route.stops
      .map((stopId) => stopMap.get(stopId))
      .filter(Boolean)
      .map((stop) => ({ lat: stop.latitude, lng: stop.longitude }));

    const encoded = polyline.encode(points.map((p) => [p.lat, p.lng]));

    return {
      ...route,
      polyline: encoded,
      polyline_points: points,
    };
  });
}

module.exports = {
  stopDefinitions,
  routeDefinitions,
  tripDefinitions,
  journeyDefinitions,
  buildRoutesWithGeometry,
};
